### ISSUE TITLE
Exception after upgrading rrdtool from 0.1.1 to 0.1.2

### ISSUE THREAD

**Issue by sachilles** [commx/python-rrdtool#4]
Hi,

thanks for providing this useful library. I'm using it on a Raspberry PI to plot temperature data over a webpage. However, after upgrading to version 0.1.2 using pip the library does not work and my small app logs messages like this

```
AttributeError: 'module' object has no attribute 'graph'
```

I figured out that this problem could be related to a change in rrdtoolmodule.c in line 431 (see https://github.com/commx/python-rrdtool/blob/master/rrdtoolmodule.c#L431).

Is there a way to be able to upgrade to version 0.1.2 while having the possibility to use the graph function?

Best regards and thanks in advance

**Comment by enyone** [comment]
Same for me:
```
$ python
Python 2.7.9 (default, Mar  8 2015, 00:52:26) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rrdtool
>>> rrdtool.graph()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'graph'

```

**Comment by dstrigl** [comment]
Any solution?

**Comment by xtay573269555** [comment]
@dstrigl   using 0.1.1 instead of 0.1.2

**Comment by commx** [comment]
0.1.3 is released.

The macro `HAVE_RRD_GRAPH` was not declared in most build environments, which prevented the appropriate graphing methods to be built. This has been fixed now.

**Comment by user2589** [comment]
@sachilles,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form:
https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/commx/python-rrdtool/issues/4

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
